---
title: "Working_Project"
author: "Wafaa Lawai"
date: "2026-02-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(terra)
library(readr)
library(tidyterra)
library(classInt)
```

```{r}

# read in faults shapefile
faults <- vect("faults/shapefiles/FAM_Qt_Faults.shp")

# read in Alameda county shapefile
alameda <- vect("County_Boundary_-2312687860649160244/County_Boundary.shp")
```

Harmonize CRS & crop to county of interest
```{r}
faults <- project(faults, 'epsg:6417')
alameda <- project(alameda, 'epsg:6417')

alameda_faults <- crop(faults, alameda)
alameda_faults <- mask(faults, alameda)
```

Convert faults vector into a distance raster
```{r}
# createa  new raster to serve as distance raster
r <- rast(alameda, nrow = 180, ncol = 360)

dists <- distance(r, alameda_faults)

plot(dists)
plot(alameda_faults, add = TRUE, col = 'white')
```
Crop distance raster to county boundaries
```{r}
dists <- crop(dists, alameda)
dists <- mask(dists, alameda)

plot(dists)
plot(alameda_faults, add = TRUE, col = 'white')
```
Read in & tidy population data
```{r}
pop <- read.csv("alameda_pop.csv", header = FALSE)
head(pop)

pop <- t(pop)
pop <- as.data.frame(pop)

colnames(pop) <- c("Tract", "Population")
pop <- pop[-1,]

```

Create a separate ID column for population data
```{r}
pop$ID <- pop$Tract

for (i in 1:379) {
  pop$ID[i] <- parse_number(pop$ID[i])
  pop$Population[i] <- parse_number(pop$Population[i])
}

pop$Population <- as.numeric(pop$Population)

```

Area data

```{r}
area <- vect("AlamedaTracts.geojson")

area$DIST_NAME

for (i in 1:378) {
  area$DIST_NAME[i] <- parse_number(area$DIST_NAME[i])
}

```

Merge population data into spatvector with land area

```{r}
colnames(pop) <- c("Tract", "Population", "DIST_NAME")

tracts <- merge(area, pop, by = "DIST_NAME")
```

Calculate density

```{r}

tracts$density <- tracts$Population / tracts$area

# density <- density %>% 
#   mutate(density = Population / area)
```

boop
```{r}
h <- classIntervals(tracts$density, n = 5, style = 'quantile')

plot(tracts, "density", breakby = 'cases')
```

Turn this into a raster

```{r}

tracter <- rasterize(tracts, r, "density")

```

